### ISSUE TITLE
Matching a key and unknown value from a map

### ISSUE THREAD

**Issue by jakemcc** [bfontaine/grape#10]
Hi there,

`grape` has been pretty useful. Thanks for creating it.

I frequently find myself wanting to search my codebase for entries in literal maps where I know the key (a particular keyword) but I'm unsure the value. I can sort of use grep/ripgrep to do this but since those tools don't understand Clojure's shape, the output is somewhat painful to read.

I've tried to use `grape` to do this and have failed to come up with a query that does this. I'll illustrate what I'm trying to below.

The following literal map exists in a file in my codebase.

```clojure
{:key [1 2 3]
 :another :value}
```

 I'd like to do something like `grape ':key $' file.clj` and have it print `:key [1 2 3]`.

Is there a way to do an operation like this?

**Comment by bfontaine** [comment]
Hello, no, `grape` is built around the idea that a pattern is a single Clojure expression, so unfortunately it’s not possible to do things like `grape 'a b' file.clj`.
