### ISSUE TITLE
ClojureScript version?

### ISSUE THREAD

**Issue by mauricioszabo** [bfontaine/grape#5]
I believe it's quite easy to port - I'm willing to do it, so I'm opening this issue to ask if this could be interesting for you.

Thanks for the library, it seems a great idea and I'm quite excited to see it in action :)

**Comment by bfontaine** [comment]
Oh yes that would be great!

**Comment by anonimitoraf** [comment]
Seems to work for Clojurescript for me. Or am I missing something?
![image](https://user-images.githubusercontent.com/15933322/106767852-6a9d9200-668f-11eb-94b7-80b9f15e589f.png)

Also, thanks for the library! I might write an Emacs wrapper for it :)

**Comment by mauricioszabo** [comment]
@anonimitoraf it's not that the current version don't work to find code in ClojureScript. Is most that I want a ClojureScript version of the current library, so we could embeded into editors' toolings (for editors like VSCode where plug-ins are written in JS)

**Comment by anonimitoraf** [comment]
Oh, I see. Using it as a lib.

If there was a cljs version though, how would you go about writing a vscode plugin for it? Import grape as a js dependency?

**Comment by mauricioszabo** [comment]
Or just write the plug-in in ClojureScript. I'm doing this with Chlorine (Atom) and Clover (VSCode) and it's a great experience :)

**Comment by anonimitoraf** [comment]
Interesting! I'll check out how you wrote Clover

**Comment by bfontaine** [comment]
I’m closing this issue for now since nobody is actively working on it.
