### ISSUE TITLE
context-less format for parsing

### ISSUE THREAD

**Issue by SevereOverfl0w** [bfontaine/grape#7]
Just trying to integrate this into vim.

To do so I need to configure an errorformat.  It would be useful if grape could produce contextless output like grep, so the file would be repeated for each match.  It's OK to have a mutli-line match after that:

```
file.clj:line: (let [
a 10]
a)
```

**Comment by bfontaine** [comment]
Sorry I didn’t comment earlier but: I saw the issue, I just don’t have a lot of time right now 😉

**Comment by SevereOverfl0w** [comment]
I no longer need this, I figured out how to do it with vim's errorformat: `'%+P%f:,%l: %m,%-Q'`
