### ISSUE TITLE
Grep by non-qualified name

### ISSUE THREAD

**Issue by mauricioszabo** [bfontaine/grape#8]
I'm trying to check for duplicated code and also wrong aliases. So, I'm trying to run:

```
grape -u '(my-function $&)' src
```

But the problem is that `my-function` can be imported from aliases or from `:refer`, and also these aliases are not normalized in my project. Can we support something like 
```
grape -u '(*/my-function $&)' src

# or...
grape -u '(#regex"(.+/|)" my-function $&)' src

# or even
grape -u '($symbol/my-function $&)' src

# or maybe combine the one above with "or"

grape -u '($or[$symbol/my-function my-function] $&)' src
```

So it can mix a "dynamic namespace part" of the symbol and a "static symbol name"?

Also, thanks again for the project!

**Comment by bfontaine** [comment]
Hello, if I’m not wrong this usage is covered by `grasp`, as documented here: https://github.com/borkdude/grasp#find-usages-based-on-resolved-symbol
